name: PackageMaker
version: 0.9
date: 2018-10-02
description: |
    A GAP package for creating new GAP packages

authors:
    - name: Max Horn
      url: https://www.quendi.de/math

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2018.02.14"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "io"
      version: ">= 3.0"
      url: "https://gap-packages.github.io/io"

www: https://gap-system.github.io/PackageMaker
readme: README.md
packageinfo: https://gap-system.github.io/PackageMaker/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/PackageMaker/releases/download/v0.9/PackageMaker-0.9.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Hor18</span>]   <b class='BibAuthor'>Horn, M.</b>,
     <i class='BibTitle'>PackageMaker, A GAP package for creating new GAP packages,
             Version 0.9</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-system.github.io/PackageMaker">https://gap-system.github.io/PackageMaker</a></span>.
    </p>
    

bibtex: |
    @misc{ PackageMaker0.9,
      author =           {Horn, M.},
      title =            {{PackageMaker},  A  GAP  package  for creating new GAP
                          packages, {V}ersion 0.9},
      month =            {Oct},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href      {https://gap-system.github.io/PackageMaker}
                          {\texttt{https://gap-system.github.io/}\discretionary
                          {}{}{}\texttt{PackageMaker}}},
      printedkey =       {Hor18}
    }

